dubbo:
  registry:
    address: zookeeper://192.168.131.128:2181
  application:
    name: shop_sso
  consumer:
    check: false
    timeout: 2000
server:
  port: 8084
spring:
  redis:
    host: 192.168.131.128
    password: root