server:
  port: 8088
spring:
  redis:
    host: 192.168.131.128
    password: root
dubbo:
  registry:
    address: zookeeper://192.168.131.128:2181
    check: false
  consumer:
    timeout: 1000
    check: false
  application:
    name: shop_order