server:
  port: 8086
spring:
  redis:
    host: 192.168.131.128
    password: root
dubbo:
  application:
    name: shop_cart
  registry:
    address: zookeeper://192.168.131.128:2181
  consumer:
    check: false
    timeout: 1000