server:
  port: 8085
dubbo:
  application:
    name: shop_back
  registry:
    address: zookeeper://192.168.131.128:2181
  consumer:
    check: false
    timeout: 1000
spring:
  thymeleaf:
    cache: false
    mode: HTML5
